### ISSUE TITLE
Example of a json file please?

### ISSUE THREAD

**Issue by alslonik** [Reedwarbler/GAPPadder#4]
Is it possible to post an example of a json file that is needed for GapPadder run?
I do not mean a general json format which I can obviously google, but a specific one... I am pretty new in the field of bioinfo, so if possible would appreciate some help..
Many thanks!

**Comment by simoncchu** [comment]
You can follow this one:
https://github.com/Reedwarbler/GAPPadder/blob/master/configuration.json

**Comment by alslonik** [comment]
THANK YOU!!!
