### ISSUE TITLE
Long and short reads for Gap filling 

### ISSUE THREAD

**Issue by alslonik** [Reedwarbler/GAPPadder#5]
Hi, 

I am sorry if the question that I am asking has been in the paper, and I just missed the point but:

I have two types of reads  and I want to to fill the gaps in Chromium 10x assembly - 
1. Illumina PE reads 
2. PacBio reads. 
Gappadder needs the alignments of the reads to be done before it fills the gaps. Therefore I am going to run bwa/bowtie on the Illumina reads (10x assembler does not output bam alignment files).
 What about the long reads? Can I use them to fill the gaps too?

Thanks

**Comment by simoncchu** [comment]
Hi, 
GAPPadder is designed for short reads only. So it cannot be used to fill the gap with long reads at the current stage.
