### ISSUE TITLE
What does "std" stand for?

### ISSUE THREAD

**Issue by e-cvgr** [Reedwarbler/GAPPadder#7]
Hi,
In configuration.json at lines 18-19 there are 2 parameters for the bam file. I suppose that "is" means insertion dimension, but I really can't unterstand the meaning of "std".
I want to run GAPPadder to its full potential, what I have to put for std?
Thank you in advance

**Comment by simoncchu** [comment]
Hi,
"is" means mean insert size of the read pairs. And "std" is the standard derivation of the insert size.

**Comment by e-cvgr** [comment]
Thank you!
